### ISSUE TITLE
exceptions raised at shutdown

### ISSUE THREAD

**Issue by ics** [abusesa/idiokit#14]
When stopping an AbuseHelper instance with ```sudo su abusehel -s /bin/bash -c 'botnet stop /full/path'``` some threads raise exceptions. 
Traceback from startup log:
```python
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last): 
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run 
  File "/usr/local/lib/python2.7/dist-packages/idiokit/threadpool.py", line 100, in _thread
  File "/usr/local/lib/python2.7/dist-packages/idiokit/_selectloop.py", line 48, in asap
<type 'exceptions.AttributeError'>: 'thread._local' object has no attribute 'current'
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last): 
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run 
  File "/usr/local/lib/python2.7/dist-packages/idiokit/idiokit.py", line 161, in throw
  File "/usr/local/lib/python2.7/dist-packages/idiokit/idiokit.py", line 550, in __init__
  File "/usr/local/lib/python2.7/dist-packages/idiokit/idiokit.py", line 381, in _pipe
  File "/usr/local/lib/python2.7/dist-packages/idiokit/idiokit.py", line 119, in add 
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last): 
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run 
  File "/usr/local/lib/python2.7/dist-packages/idiokit/threadpool.py", line 100, in _thread
  File "/usr/local/lib/python2.7/dist-packages/idiokit/_selectloop.py", line 48, in asap
<type 'exceptions.AttributeError'>: 'thread._local' object has no attribute 'current'
```

I'm running idiokit https://github.com/abusesa/idiokit/commit/5f223bdcf75e58b873d99759c34ce58170324e88 .

**Comment by jviide-work** [comment]
Thank you. Which platform are you using?

**Comment by ics** [comment]
Ubuntu 14.04.3 LTS, Python 2.7.6

**Comment by jviide-work** [comment]
Commits b10489c and 8173274 seem to fix this issue.

**Comment by ics** [comment]
I can confirm that. Running https://github.com/abusesa/idiokit/commit/817327458d14d618791fa58ce3a8e6063bd480fb without issues.

**Comment by jviide-work** [comment]
\o/
