### ISSUE TITLE
XMPP connection fails for server with hostname only in /etc/hosts

### ISSUE THREAD

**Issue by tevas** [abusesa/idiokit#21]
In case the xmpp server hostname is only in /etc/hosts, finding the srv record with dns.srv previously returned [] but since 6adb9fa73a266cf5fdd685badfb0fa7de7137402 it now throws idiokit.dns._dns.NoData

Example (jid changed):
```
2016-04-01 19:24:28Z test.bridge[27504] INFO Connecting to XMPP dst server with JID 'user@host'
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL Traceback (most recent call last):
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 308, in execute
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     return self.run()
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/bots/bridgebot/bridgebot.py", line 111, in run
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     return idiokit.main_loop(self.main())
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 296, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/bots/bridgebot/bridgebot.py", line 96, in main
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     self.xmpp_dst_room)
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 296, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/bots/bridgebot/bridgebot.py", line 75, in _join
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     ssl_ca_certs=ca_certs)
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 296, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/xmpp/__init__.py", line 113, in connect
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     sock = yield _get_socket(jid.domain, host, port, timeout)
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 296, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/xmpp/__init__.py", line 63, in _get_socket
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     results = yield _resolve.resolve(domain, host, port)
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 296, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/xmpp/_resolve.py", line 22, in resolve
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     srv_records = yield dns.srv("_xmpp-client._tcp." + domain)
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 296, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/dns/_dns.py", line 944, in srv
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     _, answers, _ = yield resolver.query(name, SRV.code)
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 298, in _next
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     next = require_stream(self._gen.send(peel_args(args)))
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/dns/_dns.py", line 833, in query
2016-04-01 19:24:28Z test.bridge[27504] CRITICAL     raise NoData("no data")
```
This causes idiokit.xmpp._resolve.resolve() to throw the exception. It should apparently be catched in idiokit.xmpp._resolve.resolve() in the same way as the other dns errors.
```
    try:
        srv_records = yield dns.srv("_xmpp-client._tcp." + domain)
    except (dns.ResponseError, dns.DNSTimeout):
        srv_records = []
```

**Comment by janikenttala** [comment]
A note: bots also have a parameter to define the xmpp-server IP.
